config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :flights
  devise_for :users
  resources :airplanes
  resources :flights
  
  root 'flights#index'

end

app/models/airplane.rb
class Airplane < ApplicationRecord
    has_many :flights
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flight.rb
class Flight < ApplicationRecord
    belongs_to :user, :optional => true
    belongs_to :airplanes, :optional => true
    has_many :reservations

end

app/models/reservation.rb
class Reservation < ApplicationRecord
    belongs_to :flight, :optional => true
  belongs_to :user, :optional => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :flights
  has_many :reservations
  end

app/controllers/airplanes_controller.rb
class AirplanesController < ApplicationController
  before_action :set_airplane, only: [:show, :edit, :update, :destroy]

  # GET /airplanes
  # GET /airplanes.json
  def index
    @airplanes = Airplane.all
  end

  # GET /airplanes/1
  # GET /airplanes/1.json
  def show
  end

  # GET /airplanes/new
  def new
    @airplane = Airplane.new
  end

  # GET /airplanes/1/edit
  def edit
  end

  # POST /airplanes
  # POST /airplanes.json
  def create
    @airplane = Airplane.new(airplane_params)

    respond_to do |format|
      if @airplane.save
        format.html { redirect_to @airplane, notice: 'Airplane was successfully created.' }
        format.json { render :show, status: :created, location: @airplane }
      else
        format.html { render :new }
        format.json { render json: @airplane.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /airplanes/1
  # PATCH/PUT /airplanes/1.json
  def update
    respond_to do |format|
      if @airplane.update(airplane_params)
        format.html { redirect_to @airplane, notice: 'Airplane was successfully updated.' }
        format.json { render :show, status: :ok, location: @airplane }
      else
        format.html { render :edit }
        format.json { render json: @airplane.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airplanes/1
  # DELETE /airplanes/1.json
  def destroy
    @airplane.destroy
    respond_to do |format|
      format.html { redirect_to airplanes_url, notice: 'Airplane was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_airplane
      @airplane = Airplane.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def airplane_params
      params.require(:airplane).permit(:name, :rows, :columns)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: [:show, :edit, :update, :destroy]

  # GET /flights
  # GET /flights.json
  def index
    @flights = Flight.all
  end

  # GET /flights/1
  # GET /flights/1.json
  def show
  end

  # GET /flights/new
  def new
    @flight = current_user.flights.build
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights
  # POST /flights.json
  def create
    @flight = current_user.flights.build(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1
  # PATCH/PUT /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def flight_params
      params.require(:flight).permit(:date, :flightnumber, :departure, :departureTime, :arrival, :arrivalTime, :plane, :seat)
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reservation_params
      params.fetch(:reservation, {})
    end
end

app/helpers/airplanes_helper.rb
module AirplanesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boring_airlines_helper.rb
module BoringAirlinesHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/airplanes/_form.html.erb
<%= form_with(model: airplane, local: true) do |form| %>
  <% if airplane.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(airplane.errors.count, "error") %> prohibited this airplane from being saved:</h2>

      <ul>
      <% airplane.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :rows %>
    <%= form.number_field :rows %>
  </div>

  <div class="field">
    <%= form.label :columns %>
    <%= form.number_field :columns %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/airplanes/edit.html.erb
<h1>Editing Airplane</h1>

<%= render 'form', airplane: @airplane %>

<%= link_to 'Show', @airplane %> |
<%= link_to 'Back', airplanes_path %>

app/views/airplanes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Airplanes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Rows</th>
      <th>Columns</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @airplanes.each do |airplane| %>
      <tr>
        <td><%= airplane.name %></td>
        <td><%= airplane.rows %></td>
        <td><%= airplane.columns %></td>
        <td><%= link_to 'Show', airplane %></td>
        <td><%= link_to 'Edit', edit_airplane_path(airplane) %></td>
        <td><%= link_to 'Destroy', airplane, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Airplane', new_airplane_path %>

app/views/airplanes/new.html.erb
<h1>New Airplane</h1>

<%= render 'form', airplane: @airplane %>

<%= link_to 'Back', airplanes_path %>

app/views/airplanes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @airplane.name %>
</p>

<p>
  <strong>Rows:</strong>
  <%= @airplane.rows %>
</p>

<p>
  <strong>Columns:</strong>
  <%= @airplane.columns %>
</p>

<%= link_to 'Edit', edit_airplane_path(@airplane) %> |
<%= link_to 'Back', airplanes_path %>

app/views/flights/_form.html.erb
<%= form_with(model: flight, local: true) do |form| %>
  <% if flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% flight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :flightnumber %>
    <%= form.number_field :flightnumber %>
  </div>

  <div class="field">
    <%= form.label :departure %>
    <%= form.text_field :departure %>
  </div>

   <div class="field">
    <%= form.label :departureTime %>
    <%= form.text_field :departureTime %>
  </div>

  <div class="field">
    <%= form.label :arrival %>
    <%= form.text_field :arrival %>
  </div>

  <div class="field">
    <%= form.label :arrivalTime %>
    <%= form.text_field :arrivalTime %>
  </div>

  <div class="field">
    <%= form.label :plane %>
    <%= form.number_field :plane %>
  </div>

  <div class="field">
    <%= form.label :seat %>
    <%= form.number_field :seat, within: 1..19 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Flights</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>| Flightnumber |</th>
      <th>Departure</th>
      <th>| DepartureTime |</th>
      <th>Arrival</th>
       <th>| ArrivalTime |</th>
      <th>Plane</th>
      <th>| Seat |</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= flight.date %></td>
        <td><%= flight.flightnumber %></td>
        <td><%= flight.departure %></td>
        <td><%= flight.departureTime %></td>
        <td><%= flight.arrival %></td>
        <td><%= flight.arrivalTime %></td>
        <td><%= flight.plane %></td>
        <td><%= flight.seat %></td>
        <td><%= link_to 'Show', flight %></td>
        <td><%= link_to 'Edit', edit_flight_path(flight) %></td>
        <td><%= link_to 'Destroy', flight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flight', new_flight_path %>

app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Back', flights_path %>

app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @flight.date %>
</p>

<p>
  <strong>Flightnumber:</strong>
  <%= @flight.flightnumber %>
</p>

<p>
  <strong>Departure:</strong>
  <%= @flight.departure %>
</p>

<p>
  <strong>Departure Time:</strong>
  <%= @flight.departureTime %>
</p>

<p>
  <strong>Arrival:</strong>
  <%= @flight.arrival %>
</p>

<p>
  <strong>Arrival Time:</strong>
  <%= @flight.arrivalTime %>
</p>

<p>
  <strong>Plane:</strong>
  <%= @flight.plane %>
</p>

<p>
  <strong>Seat:</strong>
  <%= @flight.seat %>
</p>

<%= link_to 'Edit', edit_flight_path(@flight) %> |
<%= link_to 'Back', flights_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirlineServer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %> 

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
   
      <p class="notice"><%= notice %></p> 
      <p class="alert"><%= alert %></p>
    <%# part of devise displays messages and alerts to user %>
  <body>
    <%= yield %>
  </body>
</html>

app/views/reservations/_form.html.erb
<%= form_with(model: reservation, local: true) do |form| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>